[build]
publish = "public"
command = "npm run build"

[build.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"
NODE_ENV = "development"