[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "14.16.0"

[context.production.environment]
HUGO_ENV = "production"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"


[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
