backend:
  name: git-gateway
  branch: dev
  site_domain: bsidestlv.netlify.com

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "sponsors" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Sponsors" # Used in the UI, ie.: "New Post"
    folder: "content/sponsors" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["titanium" ,"platinum" ,"gold" ,"silver" ,"venue"] }
      - {label: "Website", name: "website", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
